#!/bin/sh
#
# set ACPI Wakeup time
# usage: setwakeup.sh seconds
#    seconds - number of seconds from epoch to UTC time (time_t time format)

/sbin/hwclock --systohc --utc            # set bios clock to system time
echo 0  > /sys/class/rtc/rtc0/wakealarm  # clear alarm
echo $1 > /sys/class/rtc/rtc0/wakealarm  # write the waketime
